default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: todokelz
  password: "202520"
  host: localhost

development:
  <<: *default
  database: todolistapp_development

test:
  <<: *default
  database: todolistapp_test

production:
  <<: *default
  database: todolistapp_production
  username: todokelz
  password: <%= ENV['TODOLISTAPP_DATABASE_PASSWORD'] %>
